CREATE DATABASE RedeSocial
GO

USE RedeSocial
GO

CREATE TABLE TipoUsuario
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(),
    Cargo NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE Usuario
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(),
    Nome NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL,
    Senha NVARCHAR(MAX) NOT NULL,
    Foto NVARCHAR(MAX) NOT NULL,

    IdTipoUsuario UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdTipoUsuario) REFERENCES TipoUsuario(Id)
);
GO

CREATE TABLE Post
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(),
    Texto NVARCHAR(MAX) NOT NULL,
    Imagem NVARCHAR(MAX) NOT NULL,

    IdUsuario UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE Comentario
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(),
    Texto NVARCHAR(MAX) NOT NULL,

    IdPost UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdPost) REFERENCES Post(Id),
    IdUsuario UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE Curtida
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(),

    IdPost UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdPost) REFERENCES Post(Id),
    IdUsuario UNIQUEIDENTIFIER NOT NULL, FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
);
GO



